# Generated by Django 2.1.7 on 2019-02-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('videofile', models.FileField(null=True, upload_to='videos', verbose_name='')),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('deskripsi_video', models.TextField()),
            ],
        ),
    ]
