# Generated by Django 2.1.7 on 2019-02-14 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoclass',
            name='posted_by',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
